server:
  port: 5000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  application:
    name: shop-admin
  cloud:
    nacos:
      discovery:
        server-addr: http://10.1.8.34:8848
  redis:
    host: 10.1.8.34 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  datasource:
    url: jdbc:mysql://10.1.8.34:3306/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时
minio:
  endpoint: http://locahost:9000 #MinIO服务所在地址
  bucketName: shop #存储桶名称
  accessKey: fDRwk18sOCJKoAbl4gjk #访问的key
  secretKey: X6IdzqSBQMHxOuxjBzS868GaPdsJshkOEUWmOqMh #访问的秘钥