server:
  port: 8301
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: shop-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://10.1.8.34:8848

