server:
  port: 8401
spring:
  application:
    name: shop-gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: http://10.1.8.34:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: shop-auth
          uri: lb://shop-auth
          predicates:
            - Path=/shop-auth/**
          filters:
            - StripPrefix=1
        - id: shop-admin
          uri: lb://shop-admin
          predicates:
            - Path=/shop-admin/**
          filters:
            - StripPrefix=1
        - id: shop-portal
          uri: lb://shop-portal
          predicates:
            - Path=/shop-portal/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8401/shop-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 10.1.8.34
    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/shop-auth/oauth/token"
      - "/shop-auth/rsa/publicKey"
      - "/shop-search/**"
      - "/shop-portal/sso/login"
      - "/shop-portal/sso/register"
      - "/shop-portal/sso/getAuthCode"
      - "/shop-portal/home/**"
      - "/shop-portal/product/**"
      - "/shop-portal/brand/**"
      - "/shop-admin/admin/login"
      - "/shop-admin/admin/register"
      - "/shop-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always